# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('blank', 'Blank')], default='Blank', max_length=10),
        ),
    ]
