# Generated by Django 2.0 on 2018-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_not_banned',
            field=models.BooleanField(default=True),
        ),
    ]
