# Generated by Django 2.0 on 2018-08-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_is_not_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('transaction', 'Transaction'), ('order', 'Order'), ('feature', 'Feature'), ('insufficient money', ' Insufficient Money')], max_length=10),
        ),
    ]
