# Generated by Django 2.0 on 2018-08-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='birthday_date',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='dollar_wallet',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='domestic_card_number',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='euro_wallet',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='rial_wallet',
        ),
    ]
