# Generated by Django 2.0 on 2018-08-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manageraddedexamordernamesimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerAddedExamOrderNamesImages',
            new_name='ManagerAddedExams',
        ),
    ]
