# Generated by Django 2.0 on 2018-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtuitionfeetransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domesticpaymenttransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examtransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foreignpaymenttransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unknownpaymenttransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
