# Generated by Django 2.0 on 2018-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
