# Generated by Django 2.0 on 2018-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial_amount_account', models.FloatField(default=0)),
                ('dollar_amount_account', models.FloatField(default=0)),
                ('euro_amount_account', models.FloatField(default=0)),
            ],
        ),
    ]
