# Generated by Django 2.0 on 2018-08-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180824_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtuitionfeetransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='domesticpaymenttransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='examtransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='foreignpaymenttransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='unknownpaymenttransaction',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ApplicationTuitionFeeTransaction',
        ),
        migrations.DeleteModel(
            name='DomesticPaymentTransaction',
        ),
        migrations.DeleteModel(
            name='ExamTransaction',
        ),
        migrations.DeleteModel(
            name='ForeignPaymentTransaction',
        ),
        migrations.DeleteModel(
            name='UnknownPaymentTransaction',
        ),
    ]
