# Generated by Django 2.0 on 2018-08-24 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtuitionfeetransaction',
            name='dollar_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='applicationtuitionfeetransaction',
            name='euro_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='domesticpaymenttransaction',
            name='rial_cost',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30000000), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='examtransaction',
            name='dollar_cost',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foreignpaymenttransaction',
            name='dollar_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foreignpaymenttransaction',
            name='euro_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='unknownpaymenttransaction',
            name='rial_cost',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30000000), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
