# Generated by Django 2.0 on 2018-08-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtuitionfeetransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='currencyconverttransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='domesticpaymenttransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='examtransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='foreignpaymenttransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='rialwalletinctransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='unknownpaymenttransaction',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
    ]
