# Generated by Django 2.0 on 2018-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
