# Generated by Django 2.0 on 2018-08-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180825_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='currency_type',
            field=models.CharField(choices=[('Rial', 'rial'), ('Euro', 'euro'), ('Dollar', 'dollar')], max_length=10, null=True),
        ),
    ]
