# Generated by Django 2.0 on 2018-08-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_currencyconverttransaction_rialwalletinctransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconverttransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rialwalletinctransaction',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CurrencyConvertTransaction',
        ),
        migrations.DeleteModel(
            name='RialWalletIncTransaction',
        ),
    ]
