# Generated by Django 2.0 on 2018-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_unknownpaymenttransaction_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='wage_rate',
            field=models.FloatField(default=0),
        ),
    ]
