# Generated by Django 2.0 on 2018-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20180827_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='type',
            field=models.CharField(default='khar', max_length=50),
        ),
    ]
