# Generated by Django 2.0 on 2018-08-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180828_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtuitionfeetransaction',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='currencyconverttransaction',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='domesticpaymenttransaction',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='examtransaction',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='foreignpaymenttransaction',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='unknownpaymenttransaction',
            old_name='type',
            new_name='type_name',
        ),
    ]
