# Generated by Django 2.0 on 2018-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180828_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='type_name',
            field=models.CharField(default='khar', max_length=50),
        ),
    ]
