# Generated by Django 2.0 on 2018-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20180828_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='manager_owner',
            field=models.BooleanField(default=False),
        ),
    ]
