# Generated by Django 2.0 on 2018-08-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20180828_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtuitionfeetransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='currencyconverttransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='domesticpaymenttransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examtransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='foreignpaymenttransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rialwalletinctransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='unknownpaymenttransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
