# Generated by Django 2.0 on 2018-08-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20180829_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtuitionfeetransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='currencyconverttransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='domesticpaymenttransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='examtransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='foreignpaymenttransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rialwalletinctransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unknownpaymenttransaction',
            name='type_name_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
