# Generated by Django 2.0 on 2018-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wage_per_month',
            field=models.FloatField(default=0),
        ),
    ]
