# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-19 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('national_id', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(default='st', max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('rial_wallet', models.IntegerField(default=0)),
                ('dollar_wallet', models.IntegerField(default=0)),
                ('euro_wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
