# Generated by Django 2.0 on 2018-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
    ]
