# Generated by Django 2.0 on 2018-08-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='domestic_bank_account_id',
            new_name='domestic_card_number',
        ),
    ]
