# Generated by Django 2.0 on 2018-08-23 22:35

import apps.customer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180823_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='domestic_card_number',
            field=apps.customer.models.DomesticCardField(max_length=16, null=True, unique=True),
        ),
    ]
