# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-20 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='configuration',
        ),
    ]
