# Generated by Django 2.0 on 2018-08-24 20:18

import apps.customer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180824_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='domestic_bank_account_id',
            field=apps.customer.models.DomesticCardField(max_length=16, null=True),
        ),
    ]
