# Generated by Django 2.0 on 2018-08-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180824_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='domestic_bank_account_id',
            new_name='domestic_card_number',
        ),
    ]
