# Generated by Django 2.0 on 2018-08-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180824_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='domestic_bank_account_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
