# Generated by Django 2.0 on 2018-08-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180824_2327'),
        ('customer', '0004_auto_20180824_2023'),
    ]

    operations = [
    ]
