# Generated by Django 2.0 on 2018-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_merge_20180825_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Non Binary')], default='male', max_length=10),
        ),
    ]
